import {
  AlertTriangle,
  Bell,
  BellOff,
  Bookmark,
  BookOpen,
  Check,
  Clapperboard,
  Download,
  Flag,
  Heart,
  HeartOff,
  Library,
  Lock,
  MessageCircle,
  Palette,
  PartyPopper,
  Pause,
  Play,
  Radio,
  Target,
  Trash2,
  Trophy,
  Tv,
  Undo2,
  Upload,
  type LucideIcon,
} from "lucide-react";

/** Associe un emoji historiquement utilisé comme icône (toast, notification)
 * à une icône Lucide, pour ne pas avoir à toucher chaque appel un par un. Un
 * emoji absent de cette table s'affiche tel quel (repli sans casse). */
export const EMOJI_ICONS: Record<string, LucideIcon> = {
  "✓": Check,
  "⚠️": AlertTriangle,
  "🔒": Lock,
  "🔕": BellOff,
  "🔔": Bell,
  "🎯": Target,
  "💾": Download,
  "📥": Upload,
  "🎉": PartyPopper,
  "🔖": Bookmark,
  "🎬": Clapperboard,
  "📚": Library,
  "📖": BookOpen,
  "📡": Radio,
  "🏳️": Flag,
  "🗑": Trash2,
  "🗑️": Trash2,
  "🎨": Palette,
  "💔": HeartOff,
  "❤️": Heart,
  "↩️": Undo2,
  "🏆": Trophy,
  "▶️": Play,
  "⏸️": Pause,
  "📺": Tv,
  "💬": MessageCircle,
};
